### ISSUE TITLE
Use Solid Data Modules

### ISSUE THREAD

**Issue by michielbdejong** [jaxoncreed/ldo-react-tutorial-1#2]
If you look at https://michielbdejong.solidcommunity.net/profile/card#me you can see my `vcard:fn "Michiel de Jong"` displayed in the HTML.

But this app displays `foaf:name "Michiel B. de Jong bla"`, and when I click 'Change Name', the change is only local to this app and does not affect my public profile page (which is displayed So the predicate used by this example app is different from the predicate used by Solid OS.

It's clear that this tutorial should be using Solid Data Modules, so that its choice of predicates can stay aligned with the choice of predicates in Solid OS and other Solid apps.

**Comment by jaxoncreed** [comment]
Solid Data Modules is outside the scope of this tutorial, which is only for raw LDO.
