### ISSUE TITLE
Add Data Needs

### ISSUE THREAD

**Issue by michielbdejong** [jaxoncreed/ldo-react-tutorial-1#3]
In order to be able to launch this app from SAI, it needs to advertise its data needs.
I'll take a stab at this.

**Comment by michielbdejong** [comment]
Made a start with https://github.com/jaxoncreed/ldo-react-tutorial-1/pull/4

**Comment by jaxoncreed** [comment]
This is out of scope for the tutorial as this tutorial is only about core RDF libraries.
